# Generated by Django 4.1.7 on 2023-04-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id_alumno", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("calificacion", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
